### ISSUE TITLE
SPI error

### ISSUE THREAD

**Issue by e-coucou** [dmiddlecamp/particle_arducam#1]
Hi,
I have an issue with Arducam, only received 0xFF from it? Do you know how to check if my cam is up and running (no led!)?
Thanks for your work
Eric

**Comment by e-coucou** [comment]
an issue with wiring ... sorry ! and again many Thanks for your job !!!

**Comment by dmiddlecamp** [comment]
Hi @e-coucou ,

  I'm glad you got it working, and I'm glad the project was useful!

Happy Hacking :) 

Thanks,
David
